=== Graybeorn/SEW_JUNIO_2020/productos.dtd
<!ELEMENT productos (pizzas, bebidas, entrantes, postres)>

<!ELEMENT pizzas (pizza+)>
<!ELEMENT pizza (valorNutricional, ingrediente+)>
<!ELEMENT ingrediente (#PCDATA)>
<!ATTLIST pizza nombre CDATA #REQUIRED>
<!ATTLIST pizza imagen CDATA #REQUIRED>
<!ATTLIST pizza precio CDATA #REQUIRED>

<!ELEMENT bebidas (bebida+)>
<!ELEMENT bebida (valorNutricional)>
<!ATTLIST bebida nombre CDATA #REQUIRED>
<!ATTLIST bebida precio CDATA #REQUIRED>

<!ELEMENT entrantes (entrante+)>
<!ELEMENT entrante (valorNutricional)>
<!ATTLIST entrante nombre CDATA #REQUIRED>
<!ATTLIST entrante precio CDATA #REQUIRED>

<!ELEMENT postres (postre+)>
<!ELEMENT postre (valorNutricional)>
<!ATTLIST postre nombre CDATA #REQUIRED>
<!ATTLIST postre precio CDATA #REQUIRED>

<!ELEMENT valorNutricional EMPTY>
<!ATTLIST valorNutricional kcal CDATA #REQUIRED>
<!ATTLIST valorNutricional proteinas CDATA #IMPLIED>
<!ATTLIST valorNutricional grasas CDATA #IMPLIED>
<!ATTLIST valorNutricional saturadas CDATA #IMPLIED>
<!ATTLIST valorNutricional azucares CDATA #IMPLIED>

=== Graybeorn/SEW_JUNIO_2020/productos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productos SYSTEM "productos.dtd">
<productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="productos.xsd">
        <pizzas>
          <pizza nombre="Margarita" imagen="" precio="9.80" id="pizza1">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
            <ingrediente>Queso</ingrediente>
            <ingrediente>Oregano</ingrediente>
          </pizza>
          <pizza nombre="Cuatro quesos" imagen="" precio="11.20" id="pizza2">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
            <ingrediente>Mozzarella</ingrediente>
            <ingrediente>Gouda</ingrediente>
            <ingrediente>Queso de cabra</ingrediente>
            <ingrediente>Cabrales</ingrediente>
          </pizza>
          <pizza nombre="Barbacoa" imagen="" precio="10.80" id="pizza3">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
            <ingrediente>Mozzarella</ingrediente>
            <ingrediente>Carne picada</ingrediente>
            <ingrediente>Pimiento rojo</ingrediente>
            <ingrediente>Salsa Barbacoa</ingrediente>
            <ingrediente>Orégano</ingrediente>
          </pizza>
          <pizza nombre="Carbonara" imagen="" precio="10.80" id="pizza4">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
            <ingrediente>Mozarella</ingrediente>
            <ingrediente>Cebolla</ingrediente>
            <ingrediente>Champiñones</ingrediente>
            <ingrediente>Aceitunas negras</ingrediente>
            <ingrediente>Huevo</ingrediente>
            <ingrediente>Nata</ingrediente>
          </pizza>
          <pizza nombre="Hawaiana" imagen="" precio="10.20" id="pizza5">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
            <ingrediente>Mozzarella</ingrediente>
            <ingrediente>Jamón serrano</ingrediente>
            <ingrediente>Piña</ingrediente>
          </pizza>
          <pizza nombre="Vegetal (sin queso)" imagen="" precio="10.80" id="pizza6">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
            <ingrediente>Tomate fresco</ingrediente>
            <ingrediente>Espinacas</ingrediente>
            <ingrediente>Champiñones</ingrediente>
            <ingrediente>Nueces</ingrediente>
            <ingrediente>Aceitunas negras</ingrediente>
          </pizza>
          <pizza nombre="Siciliana" imagen="" precio="11.20" id="pizza7">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
            <ingrediente>Mozzarella</ingrediente>
            <ingrediente>Tomate fresco</ingrediente>
            <ingrediente>Cebolla</ingrediente>
            <ingrediente>Alcaparras</ingrediente>
            <ingrediente>Queso de cabra</ingrediente>
            <ingrediente>Aceite de oliva</ingrediente>
          </pizza>
        </pizzas>
  
        <bebidas>
          <bebida nombre="Coca-cola" precio="1.80" id="bebida1">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </bebida>
          <bebida nombre="Coca-cola zero" precio="1.80" id="bebida2">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </bebida>
          <bebida nombre="Fanta naranja" precio="1.80" id="bebida3">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </bebida>
          <bebida nombre="Fanta limon" precio="1.80" id="bebida4">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </bebida>
          <bebida nombre="Agua" precio="" id="bebida5">
            <valorNutricional kcal="" proteinas="1.20" grasas="" saturadas="" azucares="" />
          </bebida>
          <bebida nombre="Nestea" precio="" id="bebida6">
            <valorNutricional kcal="" proteinas="1.80" grasas="" saturadas="" azucares="" />
          </bebida>
          <bebida nombre="Estrella galicia" precio="1.80" id="bebida7">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </bebida>
          <bebida nombre="San Miguel 0,0" precio="2.00" id="bebida8">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </bebida>
        </bebidas>
        
        <entrantes>
          <entrante nombre="Nuggets de pollo (6 uds)" precio="5.60"  id="entrante1">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </entrante>
          <entrante nombre="Patatas fritas" precio="3.50" id="entrante2">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </entrante>
          <entrante nombre="Patatas 3 salsas" precio="4.50" id="entrante3">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </entrante>
          <entrante nombre="Croquetas de jamón (6 uds)" precio="6.20" id="entrante4">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </entrante>
          <entrante nombre="Mozzarella fingers (6 uds)" precio="5.20" id="entrante5">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </entrante>
          <entrante nombre="Patatas panaderas" precio="4.00" id="entrante6">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </entrante>
        </entrantes>

        <postres>
          <postre nombre="Mousse de chocolate" precio="3.60" id="postre1">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </postre>
          <postre nombre="Tarta de manzana" precio="3.80" id="postre2">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </postre>
          <postre nombre="Tarta de queso" precio="3.80" id="postre3">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </postre>
          <postre nombre="Flan de huevo" precio="3.20" id="postre4">
            <valorNutricional kcal="" proteinas="" grasas="" saturadas="" azucares="" />
          </postre>
        </postres>
</productos>
